<a href="https://colab.research.google.com/github/Sanjana-Sarma/IT-Automation-with-Pyhon---Google-/blob/main/July19Class_pandas%26numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

frame1 = pd.DataFrame({'ID':['ball', 'pencil', 'pen', 'eraser', 'mug'], 'price':['20.54', '2.32', '1.50', '4.50', '60.34']})
frame1


ID  price
0    ball  20.54
1  pencil   2.32
2     pen   1.50
3  eraser   4.50
4     mug  60.34

In [ ]:
frame2 = pd.DataFrame({'ID':['ball', 'pencil', 'mug', 'rose'], 'Colour':['blue', 'brown', 'white', 'red']})
frame2

ID Colour
0    ball   blue
1  pencil  brown
2     mug  white
3    rose    red

In [ ]:
pd.merge(frame1, frame2)

ID  price Colour
0    ball  20.54   blue
1  pencil   2.32  brown
2     mug  60.34  white

In [ ]:
frame1 = pd.DataFrame({'ID':["ball", 'pencil', 'pen', 'eraser', 'mug'],
                       'Price':['20.20', '2.50', '10.50', '5.00', '30.20'],
                       'Colour':['blue', 'brown', 'blue', 'white', 'orange']})
frame1

ID  Price  Colour
0    ball  20.20    blue
1  pencil   2.50   brown
2     pen  10.50    blue
3  eraser   5.00   white
4     mug  30.20  orange

In [ ]:
frame2 = pd.DataFrame({'ID':['pencil', 'pen', 'ball', 'mug'],
                       'brand':['UFH', 'FMF', 'FHCJ', 'FHD']})
frame2

ID brand
0  pencil   UFH
1     pen   FMF
2    ball  FHCJ
3     mug   FHD

In [ ]:
pd.merge(frame1, frame2)

ID  Price  Colour brand
0    ball  20.20    blue  FHCJ
1  pencil   2.50   brown   UFH
2     pen  10.50    blue   FMF
3     mug  30.20  orange   FHD

In [ ]:
pd.merge(frame1, frame2, on = 'ID')

ID  Price  Colour brand
0    ball  20.20    blue  FHCJ
1  pencil   2.50   brown   UFH
2     pen  10.50    blue   FMF
3     mug  30.20  orange   FHD

In [ ]:
frame2

ID brand
0  pencil   UFH
1     pen   FMF
2    ball  FHCJ
3     mug   FHD

In [ ]:
frame2.columns = ['brand', 'sid']
frame2

brand   sid
0  pencil   UFH
1     pen   FMF
2    ball  FHCJ
3     mug   FHD

In [ ]:
pd.merge(frame1, frame2, left_on = 'ID', right_on = 'sid')

Empty DataFrame
Columns: [ID, Price, Colour, brand, sid]
Index: []

In [ ]:
frame2.columns = ['brand', 'ID']
frame2

brand    ID
0  pencil   UFH
1     pen   FMF
2    ball  FHCJ
3     mug   FHD

In [ ]:
pd.merge(frame1, frame2, on = 'ID', how = 'outer')

ID  Price  Colour   brand
0    ball  20.20    blue     NaN
1  pencil   2.50   brown     NaN
2     pen  10.50    blue     NaN
3  eraser   5.00   white     NaN
4     mug  30.20  orange     NaN
5     UFH    NaN     NaN  pencil
6     FMF    NaN     NaN     pen
7    FHCJ    NaN     NaN    ball
8     FHD    NaN     NaN     mug

In [ ]:
pd.merge(frame1, frame2, on = ['brand', 'ID'], how = 'outer')

KeyError: ignored

In [ ]:
frame2.columns = ['ID', 'brand']
frame2

ID brand
0  pencil   UFH
1     pen   FMF
2    ball  FHCJ
3     mug   FHD

In [ ]:
array1 = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
array2 = array1 + 6
result_array = np.concatenate([array1, array2], axis = 0)
result_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [ ]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
array2

array([[ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [ ]:
ser1 = pd.Series(np.random.rand(4), index = [1, 2, 3, 4])
ser1

1    0.518131
2    0.081149
3    0.685492
4    0.777980
dtype: float64

In [ ]:
ser2 = pd.Series(np.random.rand(4), index = [5, 6, 7, 8])
ser2

5    0.970991
6    0.593867
7    0.964627
8    0.676133
dtype: float64

In [ ]:
pd.concat([ser1, ser2])

1    0.518131
2    0.081149
3    0.685492
4    0.777980
5    0.970991
6    0.593867
7    0.964627
8    0.676133
dtype: float64

In [ ]:
pd.concat([ser1, ser2], axis = 1)

0         1
1  0.518131       NaN
2  0.081149       NaN
3  0.685492       NaN
4  0.777980       NaN
5       NaN  0.970991
6       NaN  0.593867
7       NaN  0.964627
8       NaN  0.676133

In [ ]:
pd.concat([ser1, ser2], keys=[1,2])

1  1    0.518131
   2    0.081149
   3    0.685492
   4    0.777980
2  5    0.970991
   6    0.593867
   7    0.964627
   8    0.676133
dtype: float64

In [ ]:
pd.concat([ser1, ser2], keys=[1,2], axis=1)

1         2
1  0.518131       NaN
2  0.081149       NaN
3  0.685492       NaN
4  0.777980       NaN
5       NaN  0.970991
6       NaN  0.593867
7       NaN  0.964627
8       NaN  0.676133

In [ ]:
ser1 = pd.Series(np.random.rand(5), index=['1','2','3','4','5'])
ser1

1    0.645791
2    0.950592
3    0.359782
4    0.454420
5    0.246871
dtype: float64

In [ ]:
ser2 = pd.Series(np.random.rand(4), index = ['5','6','7','8'])
ser2

5    0.790184
6    0.232511
7    0.300753
8    0.986480
dtype: float64

In [ ]:
ser1.combine_first(ser2)

1    0.645791
2    0.950592
3    0.359782
4    0.454420
5    0.246871
6    0.232511
7    0.300753
8    0.986480
dtype: float64

In [ ]:
ser2.combine_first(ser1)

1    0.645791
2    0.950592
3    0.359782
4    0.454420
5    0.790184
6    0.232511
7    0.300753
8    0.986480
dtype: float64

In [ ]:
ser1[:3].combine_first(ser2[:3])

1    0.645791
2    0.950592
3    0.359782
5    0.790184
6    0.232511
7    0.300753
dtype: float64

In [ ]:
results = [12,34,19,35,67,35,89,24,38,89,12,54,25,45,54,25,65,77,88,99]
bins = [0,25,50,75,100]
cat = pd.cut(results, bins)
cat

[(0, 25], (25, 50], (0, 25], (25, 50], (50, 75], ..., (0, 25], (50, 75], (75, 100], (75, 100], (75, 100]]
Length: 20
Categories (4, interval[int64, right]): [(0, 25] < (25, 50] < (50, 75] < (75, 100]]

In [ ]:
cat.categories


IntervalIndex([(0, 25], (25, 50], (50, 75], (75, 100]], dtype='interval[int64, right]')

In [ ]:
cat.codes

array([0, 1, 0, 1, 2, 1, 3, 0, 1, 3, 0, 2, 0, 1, 2, 0, 2, 3, 3, 3],
      dtype=int8)

In [ ]:
pd.value_counts(cat)

(0, 25]      6
(25, 50]     5
(75, 100]    5
(50, 75]     4
dtype: int64

In [ ]:
rand_data = pd.DataFrame({
    '1': np.random.rand(1000),
    '2': np.random.randn(1000),
    '3': np.random.randint(1, 100, size=1000)
})
rand_data

1         2   3
0    0.256613 -1.309847  39
1    0.051022  0.394456  31
2    0.023662  0.650220   7
3    0.244215 -0.398301  81
4    0.308180 -0.062078  74
..        ...       ...  ..
995  0.389214 -0.177897  30
996  0.417660 -0.963747  84
997  0.146787 -0.871692  88
998  0.042168 -1.439978  53
999  0.188562  0.634514  11

[1000 rows x 3 columns]

In [ ]:
rand_data.describe()

1            2            3
count  1000.000000  1000.000000  1000.000000
mean      0.489166     0.052761    49.419000
std       0.285481     1.009991    27.882304
min       0.000654    -3.060083     1.000000
25%       0.253709    -0.644758    24.750000
50%       0.486342     0.057649    50.000000
75%       0.736922     0.755415    75.000000
max       0.995654     3.059682    99.000000

In [ ]:
rand_data[(np.abs(rand_data)>(3*rand_data.std())).any(1)]

<ipython-input-54-e2e5f25cf61e>:1: FutureWarning: In a future version of pandas all arguments of DataFrame.any and Series.any will be keyword-only.
  rand_data[(np.abs(rand_data)>(3*rand_data.std())).any(1)]


1         2   3
5    0.136346  1.180754  99
9    0.134563 -1.668327  87
10   0.948256  0.554676  91
13   0.946115 -0.285412  36
14   0.956885 -0.383584  76
..        ...       ...  ..
976  0.126739 -0.410123  89
985  0.076423  1.409906  99
986  0.928183  1.113959   2
996  0.417660 -0.963747  84
997  0.146787 -0.871692  88

[253 rows x 3 columns]

In [ ]:
rand_data[(np.abs(rand_data)>(3*rand_data.std())).any(2)]

<ipython-input-56-b8b81a0e329f>:1: FutureWarning: In a future version of pandas all arguments of DataFrame.any and Series.any will be keyword-only.
  rand_data[(np.abs(rand_data)>(3*rand_data.std())).any(2)]


ValueError: ignored